spring:
  profiles:
    active: development

---

spring:
  profiles: development
server:
  port: 11401
logging:
  file: log.log
  level:
    org:
      springframework:
        web: INFO

---
      
spring:
  profiles: test
server:
  port: 11401
logging:
  file: log.log
  level:
    org:
      springframework:
        web: INFO
      
---
      
spring:
  profiles: consolidation
server:
  port: 11401
logging:
  file: log.log
  level:
    org:
      springframework:
        web: INFO
              
---
      
spring:
  profiles: production
server:
  port: 11401
logging:
  file: log.log
  level:
    org:
      springframework:
        web: INFO